# Generated by Django 4.0.5 on 2022-06-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout_degree',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='zhp.degree'),
        ),
        migrations.AlterField(
            model_name='scout_degree',
            name='scout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='zhp.scout'),
        ),
    ]
