# Generated by Django 4.0.5 on 2022-06-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhp', '0002_alter_scout_degree_degree_alter_scout_degree_scout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='scout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout', to='zhp.scout'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='zhp.team'),
        ),
    ]
