# Generated by Django 4.0.5 on 2022-06-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_druzyny', models.CharField(max_length=100)),
                ('numer_druzyny', models.IntegerField()),
                ('data_zalozenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Harcerz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('telefon', models.CharField(max_length=9)),
                ('plec', models.CharField(max_length=10)),
                ('data_dolaczenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stopien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_stopnia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stopien_harcerza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zdobycia', models.DateField()),
                ('id_harcerz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhp.harcerz')),
                ('id_stopien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhp.stopien')),
            ],
        ),
        migrations.CreateModel(
            name='Harcerz_w_druzynie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dolaczenia', models.DateField()),
                ('id_druzyna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhp.druzyna')),
                ('id_harcerz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhp.harcerz')),
            ],
        ),
    ]
