# Generated by Django 4.0.5 on 2022-06-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harcerz',
            name='pesel',
        ),
    ]
